# Backend Dockerfile

FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install

# Build backend
FROM node:22-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN npx prisma generate
RUN npm run build:backend

# Final stage
FROM node:22-alpine AS runner
WORKDIR /app

COPY package*.json ./
RUN npm install

# Prisma client and schema
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

# Copy build output
COPY --from=builder /app/dist ./dist

# Expose port and run
EXPOSE 8000
CMD ["node", "dist/apps/backend/main.js"]