version: '3.9'

services:
  app:
    build: .
    image: node:20
    container_name: hris_prod
    working_dir: /usr/src/app
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - DATABASE_URL= ${{ secrets.DATABASE_URL }}

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${{ secrets.DATABASE_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      POSTGRES_DB: hris_dev
      POSTGRES_HOST: ${{ secrets.DATABASE_HOST }}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
