version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/dockerfile
    container_name: hris_frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080

  backend:
    build:
      context: .
      dockerfile: docker/backend/dockerfile
    container_name: hris_backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8000
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - NODE_ENV=production
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - JWT_ACCESS_TOKEN_EXPIRE=${JWT_ACCESS_TOKEN_EXPIRE}
      - JWT_REFRESH_TOKEN_EXPIRE=${JWT_REFRESH_TOKEN_EXPIRE}
      - TRIPAY_PRIVATE_KEY=${TRIPAY_PRIVATE_KEY}
      - TRIPAY_MERCHANT_CODE=${TRIPAY_MERCHANT_CODE}
      - RETURN_URL=${RETURN_URL}
