version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/dockerfile
    container_name: hris_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}

  backend:
    build:
      context: .
      dockerfile: docker/backend/dockerfile
    container_name: hris_backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/hris_dev?schema=public
      - PORT=8000
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - NODE_ENV=development
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - JWT_ACCESS_TOKEN_EXPIRE=${JWT_ACCESS_TOKEN_EXPIRE}
      - JWT_REFRESH_TOKEN_EXPIRE=${JWT_REFRESH_TOKEN_EXPIRE}
      - TRIPAY_PRIVATE_KEY=${TRIPAY_PRIVATE_KEY}
      - TRIPAY_MERCHAANT_CODE=${TRIPAY_MERCHANT_CODE}
      - RETURN_URL=${RETURN_URL}

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: hris_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
