-- AlterTable
ALTER TABLE "AbsenceLeave" ADD COLUMN     "status_expired" TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Letter" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
