export enum BankCode {
  BRI = 'BRI',
  Mandiri = 'Mandiri',
  BNI = 'BNI',
  Danamon = 'Danamon',
  Permata = 'Permata',
  BCA = 'BCA',
  Maybank = 'Maybank',
  Panin = 'Panin',
  Bukopin = 'Bukopin',
  CIMB = 'CIMB',
  UOB = 'UOB',
  OCBC = 'OCBC',
  BJB = 'BJB',
  Muamalat = 'Muamalat',
  BTN = 'BTN',
  BTPN = 'BTPN',
  Mega = 'Mega',
  SyariahMandiri = 'SyariahMandiri',
  Commonwealth = 'Commonwealth',
}
