name: cypress

on:
  workflow_run:
    workflows: ["deploy-staging"]
    types:
      - completed

jobs:
  cypress-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: ${{ secrets.CYPRESS_BASE_URL }}
          record: true
          parallel: true
          config: baseUrl=${{ secrets.CYPRESS_BASE_URL }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
