name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait 2 minute before starting tests
        run: |
          echo "Waiting 2 minute before starting Cypress tests..."
          sleep 120
          echo "Wait completed. Starting Cypress tests..."

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: ${{ secrets.CYPRESS_BASE_URL }}
          record: true
          parallel: true
          config: baseUrl=${{ secrets.CYPRESS_BASE_URL }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}