name: cypress

on:
  workflow_run:
    workflows: ["deploy"]
    types:
      - completed
  workflow_dispatch:
    
  push:
    branches: [ "main", "staging" ]
    
jobs:
  cypress-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait 1 minute for manual dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Manual dispatch detected. Waiting 1 minute before starting Cypress tests..."
          sleep 60
          echo "Wait completed. Starting Cypress tests..."

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: ${{ secrets.CYPRESS_BASE_URL }}
          record: true
          parallel: true
          config: baseUrl=${{ secrets.CYPRESS_BASE_URL }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
