name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Reset database with Prisma
        run: npx prisma migrate reset --force
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://34.50.86.184:3000'
          record: true
          parallel: true
          config: baseUrl=http://34.50.86.184:3000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
